#!/bin/sh
cp="build;jade/lib/jade.jar;lib/json-simple-1.1.1.jar;lib/junit-4.10.jar;lib/hamcrest-code-1.1.jar;lib/SAJaS.jar;repastj/repastj.jar"

javac src/*.java src/*/*.java \
  -classpath $cp \
  -d build
